In [5]:
import numpy as np
from datetime import datetime,timedelta
from netCDF4 import Dataset
#import tensorflow as tf
#from tensorflow.keras import Model, datasets, layers, models, backend
#from tensorflow import keras
from contextlib import redirect_stdout
import os, sys
import psutil, os
#import matplotlib.pyplot as plt
from cftime import num2date, date2num
import matplotlib.pyplot as plt
#! pip install shap
#! pip install visualkeras

In [9]:
#fsst = xr.open_dataset("/home/sun/data/data_all/tos_training.nc")
nr_times = 28764
f1 = Dataset('/home/sun/data/data_all/tos_training.nc')
sst = f1.variables['sst'][0:nr_times,:,:,:]
print(sst.shape)

(28764, 3, 24, 72)


In [15]:
print(sst[0, :, 0, 5])

[-0.61700439 -0.58737183 -0.46368408]


In [16]:
print(sst[1, :, 0, 5])

[-0.58737183 -0.46368408 -0.34844971]


In [17]:
print(sst[2, :, 0, 5])

[-0.46368408 -0.34844971 -0.30187988]


In [18]:
tdim, zdim, ydim, xdim = sst.shape

In [19]:
tr_x = np.swapaxes(sst, 1, 3)

In [20]:
tr_x.shape

(28764, 72, 24, 3)